const data = [
  {
    id: '1',
    firstName: 'Etan',
    lastName: 'Eastcott',
    nickname: 'Gerta',
    course: 'English',
    year: 'Senior',
  },
  {
    id: '2',
    firstName: 'Mill',
    lastName: 'Champness',
    nickname: 'Cyrill',
    course: 'Computer Science',
    year: 'Junior',
  },
  {
    id: '3',
    firstName: 'Malvin',
    lastName: 'Monroe',
    nickname: 'Marylee',
    course: 'History',
    year: 'Senior',
  },
  {
    id: '4',
    firstName: 'Teodorico',
    lastName: 'Potteridge',
    nickname: 'Hulda',
    course: 'Computer Science',
    year: 'Freshman',
  },
  {
    id: '5',
    firstName: 'Shelley',
    lastName: 'Coverlyn',
    nickname: 'Christiana',
    course: 'Computer Science',
    year: 'Sophomore',
  },
  {
    id: '6',
    firstName: 'May',
    lastName: 'Cruddace',
    nickname: 'Emmery',
    course: 'English',
    year: 'Freshman',
  },
  {
    id: '7',
    firstName: 'Carson',
    lastName: 'Bryce',
    nickname: 'Foster',
    course: 'Computer Science',
    year: 'Sophomore',
  },
  {
    id: '8',
    firstName: 'Ulick',
    lastName: 'Fisby',
    nickname: 'Jobye',
    course: 'English',
    year: 'Freshman',
  },
  {
    id: '9',
    firstName: 'Alan',
    lastName: 'Livermore',
    nickname: 'Vallie',
    course: 'English',
    year: 'Freshman',
  },
  {
    id: '10',
    firstName: 'Vlad',
    lastName: 'Coggeshall',
    nickname: 'Geraldine',
    course: 'Physics',
    year: 'Senior',
  },
  {
    id: '11',
    firstName: 'Vlad',
    lastName: 'Coggeshall',
    nickname: 'Geraldine',
    course: 'Physics',
    year: 'Senior',
  },
  {
    id: '12',
    firstName: 'Aerron',
    lastName: 'McAnulty',
    nickname: 'Mabel',
    course: 'Computer Science',
    year: 'Sophomore',
  },
  {
    id: '13',
    firstName: 'Daniella',
    lastName: 'Yegorchenkov',
    nickname: 'Alana',
    course: 'Mathematics',
    year: 'Junior',
  },
  {
    id: '14',
    firstName: 'Bryant',
    lastName: 'Gaffney',
    nickname: 'Isahella',
    course: 'History',
    year: 'Junior',
  },
  {
    id: '15',
    firstName: 'Banky',
    lastName: 'Roly',
    nickname: 'Evered',
    course: 'Mathematics',
    year: 'Sophomore',
  },
  {
    id: '16',
    firstName: 'Samaria',
    lastName: 'Beamiss',
    nickname: 'Zebadiah',
    course: 'Computer Science',
    year: 'Senior',
  },
  {
    id: '17',
    firstName: 'Vasili',
    lastName: 'Choake',
    nickname: 'Jenilee',
    course: 'History',
    year: 'Sophomore',
  },
  {
    id: '18',
    firstName: 'Shayna',
    lastName: 'Laurenz',
    nickname: 'Francisca',
    course: 'Mathematics',
    year: 'Sophomore',
  },
  {
    id: '19',
    firstName: 'Mortimer',
    lastName: 'Coomber',
    nickname: 'Joellen',
    course: 'History',
    year: 'Sophomore',
  },
  {
    id: '20',
    firstName: 'Bambi',
    lastName: 'Raffan',
    nickname: 'Gram',
    course: 'Mathematics',
    year: 'Junior',
  },
  {
    id: '21',
    firstName: 'Lyn',
    lastName: 'Luebbert',
    nickname: 'Hebert',
    course: 'History',
    year: 'Sophomore',
  },
  {
    id: '22',
    firstName: 'Lucina',
    lastName: 'De Paoli',
    nickname: 'Torre',
    course: 'Physics',
    year: 'Sophomore',
  },
  {
    id: '23',
    firstName: 'Stan',
    lastName: 'Wash',
    nickname: 'Judith',
    course: 'Mathematics',
    year: 'Senior',
  },
  {
    id: '24',
    firstName: 'Jorey',
    lastName: 'Bertholin',
    nickname: 'Kelsey',
    course: 'Physics',
    year: 'Senior',
  },
  {
    id: '25',
    firstName: 'Marnia',
    lastName: 'Muldownie',
    nickname: 'Thia',
    course: 'Computer Science',
    year: 'Senior',
  },
];

export default data;
